### ISSUE TITLE
Dot file is missing

### ISSUE THREAD

**Issue by mhallak** [cogniteam/decision_making#14]
Launch any of the fsm examples opens rqt window.
The Graph.py is looking for a non existing dot file.
Anyway, the application doesn't produce dot file.

```
roslaunch decision_making_examples fsm_wandering.launch
```
```
[ INFO] [1442837234.203258617]: Starting wandering machine...
[ INFO] [1442837234.204351572]: Turning...
INFO: Graph has been addedReading dot data from 
/home/michele/dmw/devel/share/decision_making_examples/graphs/Wandering.dot
Traceback (most recent call last):
  File "/home/michele/dmw/src/decision_making/rqt_decision_graph/src/rqt_decision_graph/graph_widget.py", line 188, in _graph_item_changed
    self._redraw_graph_view()
  File "/home/michele/dmw/src/decision_making/rqt_decision_graph/src/rqt_decision_graph/graph_widget.py", line 206, in _redraw_graph_view
    self._current_graph.load()
  File "/home/michele/dmw/src/decision_making/rqt_decision_graph/src/rqt_decision_graph/graph.py", line 55, in load
    self._create_dot_from_file(self.source)
  File "/home/michele/dmw/src/decision_making/rqt_decision_graph/src/rqt_decision_graph/graph.py", line 60, in _create_dot_from_file
    raise GraphParseException("Could not read dot file")
rqt_decision_graph.graph.GraphParseException: Could not read dot file
[ INFO] [1442837236.701614261]: Driving...
```
```
michele@apollo:~/dmw$ find . -name "*.dot"
michele@apollo:~/dmw$ ls
build  devel  src
```

**Comment by mhallak** [comment]
My problem was that I did:
```
catkin_make
```
instead of
```
catkin_make install
```
