### ISSUE TITLE
rqt_decision_graph crashes

### ISSUE THREAD

**Issue by carlosjoserg** [cogniteam/decision_making#15]
Hi, first of all, thanks for such a wonderful package. There is no official release on Indigo, but I'm using it thanks to #12. And second, the issue title is not entirely correct, let me explain.

I have Ubuntu 14.04/Indigo on two machines, I `git clone` the same code (`decision_making` package included), and I can see all examples in both PCs. 

But my example can only be rqt-graph-viewed on one of them, in the other, the `rqt_decision_graph` plugin crashes with the log I paste below. 

I've been trying to figure out what could be the difference, but can't spot it. I also found that several persons have had the `trouble in init_rank` with graphviz, but not sure this is the case.

Any idea what it could be?

---
```
Traceback (most recent call last):
  File "/home/crosales/Code/catkin_ws/src/pacman-DR54/decision_making/rqt_decision_graph/src/rqt_decision_graph/graph_widget.py", line 188, in _graph_item_changed
    self._redraw_graph_view()
  File "/home/crosales/Code/catkin_ws/src/pacman-DR54/decision_making/rqt_decision_graph/src/rqt_decision_graph/graph_widget.py", line 206, in _redraw_graph_view
    self._current_graph.load()
  File "/home/crosales/Code/catkin_ws/src/pacman-DR54/decision_making/rqt_decision_graph/src/rqt_decision_graph/graph.py", line 55, in load
    self._create_dot_from_file(self.source)
  File "/home/crosales/Code/catkin_ws/src/pacman-DR54/decision_making/rqt_decision_graph/src/rqt_decision_graph/graph.py", line 70, in _create_dot_from_file
    self.nodes, self.edges = self.dot_processor.process(dot_graph)
  File "/home/crosales/Code/catkin_ws/src/pacman-DR54/decision_making/rqt_decision_graph/src/rqt_decision_graph/dot_processor.py", line 49, in process
    self._map_dot_graph(dot_data, graphs, graphs_nodes_and_edges, cluster_nodes)
  File "/home/crosales/Code/catkin_ws/src/pacman-DR54/decision_making/rqt_decision_graph/src/rqt_decision_graph/dot_processor.py", line 175, in _map_dot_graph
    bounding_box = self._map_dot_graph(digraph_dot, graphs, graphs_nodes_and_edges, cluster_nodes)
  File "/home/crosales/Code/catkin_ws/src/pacman-DR54/decision_making/rqt_decision_graph/src/rqt_decision_graph/dot_processor.py", line 188, in _map_dot_graph
    graph = self._adjust_html_nodes_size(graph)
  File "/home/crosales/Code/catkin_ws/src/pacman-DR54/decision_making/rqt_decision_graph/src/rqt_decision_graph/dot_processor.py", line 308, in _adjust_html_nodes_size
    return graph_from_dot_data(digraph.create_dot())
  File "/home/crosales/Code/catkin_ws/src/pacman-DR54/decision_making/rqt_decision_graph/src/rqt_decision_graph/pydot.py", line 1731, in <lambda>
    lambda f=frmt, prog=self.prog: self.create(format=f, prog=prog)
  File "/home/crosales/Code/catkin_ws/src/pacman-DR54/decision_making/rqt_decision_graph/src/rqt_decision_graph/pydot.py", line 1957, in create
    status, stderr_output))
rqt_decision_graph.pydot.InvocationException: Program terminated with status: 1. stderr follows: Error: trouble in init_rank
	%0 2
	%0 6
	%0 2
	%0 7
	%0 1
	%0 2
	%0 2
	%0 7
	%0 6
	%0 7
	%0 6
	%0 2
	%0 1
	28 1
	27 1
	26 2
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 2
	25 2
	%0 3
	24start 2
	21 6
	22 3
	%0 1
	%0 3
	%0 5
	19start 5
	17 3
	%0 3
	16 3
	%0 1
	15start 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
	%0 1
```

**Comment by carlosjoserg** [comment]
Oh, I forgot to mention.
My example has a task registered so far, and when I comment out all regarding that task in the machine where it crashes, the `rqt_decision_graph` works well.
Thanks in advance!

**Comment by danerde** [comment]
Hi, Carlos.
Thanks for using our lib.

check pydot and graphviz versions on both machines. may be they are not same



                                                              Dan
Erusalimchik
----------------------------------------------------------------------------------------
System Architect at CogniTeam ltd.
email    : danerde@gmail.com
phone    : 054-630-2446
web      : http://www.cogniTeam.com/
----------------------------------------------------------------------------------------

**Comment by carlosjoserg** [comment]
Yes, they are the same.

I'm still struggling with that, haven't found what it is... I'll keep you posted.

**Comment by carlosjoserg** [comment]
Hi there, I'm trying now with the PC this used to happen, and it is working now.

There have been several system updates in between, so it is hard to tell what it was.

Closing...
